name: dmdn0
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - cudatoolkit
  - cudnn
  - tensorflow-gpu
  - tqdm
  - pyarrow
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - psutil
  - numba
  - scipy
  - pydot
  - graphviz